#[Typography]
font_family      BigBlueTerm437 Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

#[Window Layout]
window_padding_width 15
background_opacity   0.90
hide_window_decorations yes
confirm_os_window_close 0

#[Base Colors]
background            #100d0d
foreground            #f4eaea
selection_background  #ff6b6b
selection_foreground  #100d0d

#[Cursor]
cursor                #ff6b6b
cursor_text_color     #100d0d
cursor_shape          block
cursor_blink_interval 0.5

#[URL Underlines]
url_color             #ff6b6b
url_style             dashed


#[Black]
color0  #141111
color8  #45475a

#[Red]
color1  #ff6b6b
color9  #ff8f8f

#[Green]
color2  #a6e3a1
color10 #b5e8b0

#[Yellow]
color3  #f9e2af
color11 #fbe8b9

#[Blue]
color4  #89b4fa
color12 #9abefa

#[Magenta]
color5  #cba6f7
color13 #d2b3f8

#[Cyan]
color6  #89dceb
color14 #9ce1ee

#[White]
color7  #bac2de
color15 #ffffff
