exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec /usr/lib/xdg-desktop-portal -r &
exec /usr/lib/xdg-desktop-portal-wlr &
exec sunshine
exec_always autotiling
exec ags run .config/ags/Desktop.ts
exec systemctl start bluetooth
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
