exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec /usr/lib/xdg-desktop-portal -r &
exec /usr/lib/xdg-desktop-portal-wlr &
exec sunshine
exec_always autotiling
exec waybar -c ~/.config/waybar/top_config -s ~/.config/waybar/top_style.css
exec waybar -c ~/.config/waybar/bottom_config -s ~/.config/waybar/bottom_style.css
exec systemctl enable bluetooth
exec systemctl start bluetooth
