general {
    layout = dwindle
    gaps_in = 6
    gaps_out = 12
    border_size = 2
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

decoration {
    rounding = 8
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}
